interface IOptions {
  value: string;
  id: string;
  label: string;
}
export const fontSizes: IOptions[] = [
  { value: "14px", id: "14", label: "14" },
  { value: "16px", id: "16", label: "16" },
  { value: "18px", id: "18", label: "18" },
  { value: "20px", id: "20", label: "20" },
  { value: "24px", id: "24", label: "24" },
  { value: "28px", id: "28", label: "28" },
  { value: "30px", id: "30", label: "30" },
  { value: "32px", id: "32", label: "32" },
  { value: "34px", id: "34", label: "34" },
  { value: "36px", id: "36", label: "36" },
  { value: "38px", id: "38", label: "38" },
  { value: "40px", id: "40", label: "40" },
];

export const codeLanguages: IOptions[] = [
  { value: "c", id: "c", label: "C" },
  { value: "csharp", id: "c#", label: "C#" },
  { value: "cpp", id: "cpp", label: "C++" },
  { value: "php", id: "php", label: "PHP" },
  { value: "python", id: "python", label: "Python" },
  { value: "node", id: "node", label: "Node JS" },
  { value: "java", id: "java", label: "Java" },
  { value: "javascript", id: "javascript", label: "Javascript" },
];

export const themeOptions: string[] = [
  "ambiance",
  "chaos",
  "chrome",
  "cloud9_day",
  "cloud9_night_low_color",
  "cloud9_night",
  "clouds_midnight",
  "clouds",
  "cobalt",
  "crimson_editor",
  "dawn",
  "dracula",
  "dreamweaver",
  "eclipse",
  "github_dark",
  "github",
  "gob",
  "gruvbox_dark_hard",
  "gruvbox_light_hard",
  "gruvbox",
  "idle_fingers",
  "iplastic",
  "katzenmilch",
  "kr_theme",
  "kuroir",
  "merbivore_soft",
  "merbivore",
  "mono_industrial",
  "monokai",
  "nord_dark",
  "one_dark",
  "pastel_on_dark",
  "solarized_dark",
  "solarized_light",
  "sqlserver",
  "terminal",
  "textmate",
  "tomorrow_night_blue",
  "tomorrow_night_bright",
  "tomorrow_night_eighties",
  "tomorrow_night",
  "tomorrow",
  "twilight",
  "vibrant_ink",
  "xcode",
];
